### ISSUE TITLE
reference paper

### ISSUE THREAD

**Issue by cs123951** [uncbiag/mermaid#139]
Hi,
    Thank you for sharing such brilliant codes.

  Could you provide more detailed documents for implementation, such as reference papers? 
    I am a beginner to LDDMM. I have read several papers about LDDMM. But I can not figure out what method you used in the codes.

  

Thank you very much.

**Comment by marcniethammer** [comment]
Here is a pretty good summary (though not entirely up-to-date) summary of the work in your group: https://biag.cs.unc.edu/project/image-registration/

And here is a github repo which provides the papers related to the various implementations. I hope this helps.

Note also that mermaid does at the moment not run with the current pyTorch version (due to a change in the pyTorch FFT interface; 1.6 likely will run). We are working on fixing it.

**Comment by cs123951** [comment]
Got it!
Thanks a lot!
